[package]
name = "Oscilator_Mod_sin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "Oscilator_Mod_sin"
crate-type = ["rlib"]